package ExceptionHandling;

import java.util.InputMismatchException;
import java.util.Scanner;
//try,catch,finally,throw,throws
class divide{ //umesh
	public void division() throws ArithmeticException{
		Scanner sc = new Scanner(System.in);
		System.out.println("enter i = ");
		int i = sc.nextInt();
		System.out.println("enter j = ");
		int j = sc.nextInt();
		int k = i/j;
		System.out.println(k);
	}
}
public class Exceptionhandle {	//vivek
	public static void main(String[] args) {
		divide d = new divide();
		d.division();
		
		
		
		
		
		
		
		
//		try {
//			Scanner sc = new Scanner(System.in);
//			System.out.println("enter i = ");
//			int i = sc.nextInt();
//			System.out.println("enter j = ");
//			int j = sc.nextInt();
//			int k = i/j;
//			System.out.println(k);
//			System.exit(0);
//		} catch (ArithmeticException e) {
//			System.out.println("denominator acannot be zero");
//		}
//		catch(InputMismatchException e) {
//			System.out.println("denominator should be numeric value");
//		}
//		catch(Exception e) {
//			e.printStackTrace();
//		}
//		finally {
//			System.out.println("get output perfectlly");
//		}
		
	}
}
